#!/usr/bin/env ts-node
/* eslint-disable @typescript-eslint/no-var-requires */

/**
 * Generate tsconfig.json files for every packages including root.
 * Define paths and references.
 */

import path from 'path';
import fs from 'fs';
import glob from 'glob';
import shx from 'shelljs';
import { ArrayUtils } from '@axe/common';

type Pkg = {
  name: string;
  workspaces?: string[];
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
};

if (!process.env.PROJECT_CWD) {
  throw new TypeError('PROJECT_CWD env not defined');
}
const rootPath = process.env.PROJECT_CWD;

const { workspaces = [] }: Pkg = require(path.resolve(
  rootPath,
  'package.json'
));

const tsPkgs = workspaces
  .flatMap((pattern) => glob.sync(pattern))
  .map((pt) => {
    const pkg: Pkg = require(path.resolve(pt, 'package.json'));

    const everyDeps = {
      ...pkg.dependencies,
      ...pkg.devDependencies,
      ...pkg.peerDependencies,
    };

    const deps = ArrayUtils.unique(
      Object.keys(everyDeps).filter((dep) =>
        everyDeps[dep].startsWith('workspace:')
      )
    );

    return {
      name: pkg.name,
      dir: path.resolve(pt),
      relative: `./${path.join(pt)}`,
      deps,
    };
  });

// generate tsconfig.json for each package
tsPkgs.forEach(({ name, dir, deps }) => {
  const isApp = !name.startsWith('@axe/');

  const references = deps.map((dep) => {
    const tsPkg = tsPkgs.find((tp) => tp.name === dep);

    return { path: path.relative(dir, tsPkg!.dir) };
  });

  const paths = {
    [`${name}/*`]: [isApp ? './*' : './src/*'],
  };

  const tsConfigPath = path.resolve(dir, 'tsconfig.json');

  const existingTsConfig: {
    compilerOptions?: Record<string, unknown>;
    include?: string[];
  } = fs.existsSync(tsConfigPath) ? require(tsConfigPath) : {};

  const includeExts = ['ts', 'tsx', 'js', 'json'].map(
    (ext) => (isApp ? './**/*.' : './src/**/*.') + ext
  );

  fs.writeFileSync(
    tsConfigPath,
    JSON.stringify(
      {
        ...existingTsConfig,
        extends: '../../tsconfig.base.json',
        compilerOptions: {
          ...existingTsConfig.compilerOptions,
          rootDir: isApp ? undefined : './src',
          outDir: './node_modules/.cache/dist',
          tsBuildInfoFile: './node_modules/.cache/.tsbuildinfo',
          paths,
        },
        include: ArrayUtils.unique([
          ...includeExts,
          ...(existingTsConfig.include || []),
        ]),
        references,
      },
      null,
      2
    )
  );
});

// generate root tsconfig.json
fs.writeFileSync(
  path.resolve(rootPath, `tsconfig.json`),
  `/* This file is automatically generated by scripts/generators/tsconfig.js */\n${JSON.stringify(
    {
      extends: './tsconfig.base.json',
      compilerOptions: {
        noEmit: true,
        tsBuildInfoFile: './node_modules/.cache/.tsbuildinfo',
      },
      include: ['*.js', '*.json', 'scripts/**/*.js', 'config/**/*.js'],
      references: [
        {
          path: 'scripts',
        },
        ...tsPkgs.map(({ dir }) => ({
          path: path.relative(rootPath, dir),
        })),
      ],
    },
    null,
    2
  )}`
);

// format every tsconfig.json files
shx.exec(`yarn prettier -w "${rootPath}/**/tsconfig.json"`);
